# Hotel booking demand

In [1]:
import pandas as pd

## Importing and basic exploration

In [2]:
data_df = pd.read_csv("data/hotel_bookings.csv")

In [3]:
#can use shape() to get number of rows and columns
print("The dataset contains ", data_df.shape[0]," rows and ", data_df.shape[1]," columns")

The dataset contains  119390  rows and  32  columns

In [4]:
#preview dataset
data_df.head(7)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,...,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [5]:
#By default a dataframe only displays 20 columns, so even though we have more, the dataset appears truncated
#This can be changed in options
pd.set_option("display.max_columns", None)

In [6]:
data_df.head(7)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03
6,Resort Hotel,0,0,2015,July,27,1,0,2,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,0,No Deposit,NaN,NaN,0,Transient,107.0,0,0,Check-Out,2015-07-03

In [7]:
#Pandas info function
#Displays all column names, their data types, and the number of non-null values
data_df.info

<bound method DataFrame.info of                hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015
1       Resort Hotel            0        737               2015
2       Resort Hotel            0          7               2015
3       Resort Hotel            0         13               2015
4       Resort Hotel            0         14               2015
...              ...          ...        ...                ...
119385    City Hotel            0         23               2017
119386    City Hotel            0        102               2017
119387    City Hotel            0         34               2017
119388    City Hotel            0        109               2017
119389    City Hotel            0        205               2017

       arrival_date_month  arrival_date_week_number  \
0                    July                        27
1                    July                        27
2                    July                        27
3                    July                        27
4                    July                        27
...                   ...                       ...
119385             August                        35
119386             August                        35
119387             August                        35
119388             August                        35
119389             August                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0
1                               1                        0
2                               1                        0
3                               1                        0
4                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  children  babies meal country  \
0                          0       2       0.0       0   BB     PRT
1                          0       2       0.0       0   BB     PRT
2                          1       1       0.0       0   BB     GBR
3                          1       1       0.0       0   BB     GBR
4                          2       2       0.0       0   BB     GBR
...                      ...     ...       ...     ...  ...     ...
119385                     5       2       0.0       0   BB     BEL
119386                     5       3       0.0       0   BB     FRA
119387                     5       2       0.0       0   BB     DEU
119388                     5       2       0.0       0   BB     GBR
119389                     7       2       0.0       0   HB     DEU

       market_segment distribution_channel  is_repeated_guest  \
0              Direct               Direct                  0
1              Direct               Direct                  0
2              Direct               Direct                  0
3           Corporate            Corporate                  0
4           Online TA                TA/TO                  0
...               ...                  ...                ...
119385  Offline TA/TO                TA/TO                  0
119386      Online TA                TA/TO                  0
119387      Online TA                TA/TO                  0
119388      Online TA                TA/TO                  0
119389      Online TA                TA/TO                  0

        previous_cancellations  previous_bookings_not_canceled  \
0                            0                               0
1                            0                               0
2                            0                               0
3                            0                               0
4                            0                               0
...                        ...                             ...
119385                       0                               0
119386                       0                               0
119387                       0                               0
119388                       0                               0
119389                       0                               0

       reserved_room_type assigned_room_type  booking_changes deposit_type  \
0                       C                  C                3   No Deposit
1                       C                  C                4   No Deposit
2                       A                  C                0   No Deposit
3                       A                  A                0   No Deposit
4                       A                  A                0   No Deposit
...                   ...                ...              ...          ...
119385                  A                  A                0   No Deposit
119386                  E                  E                0   No Deposit
119387                  D                  D                0   No Deposit
119388                  A                  A                0   No Deposit
119389                  A                  A                0   No Deposit

        agent  company  days_in_waiting_list customer_type     adr  \
0         NaN      NaN                     0     Transient    0.00
1         NaN      NaN                     0     Transient    0.00
2         NaN      NaN                     0     Transient   75.00
3       304.0      NaN                     0     Transient   75.00
4       240.0      NaN                     0     Transient   98.00
...       ...      ...                   ...           ...     ...
119385  394.0      NaN                     0     Transient   96.14
119386    9.0      NaN                     0     Transient  225.43
119387    9.0      NaN                     0     Transient  157.71
119388   89.0      NaN                     0     Transient  104.40
119389    9.0      NaN                     0     Transient  151.20

        required_car_parking_spaces  total_of_special_requests  \
0                                 0                          0
1                                 0                          0
2                                 0                          0
3                                 0                          0
4                                 0                          1
...                             ...                        ...
119385                            0                          0
119386                            0                          2
119387                            0                          4
119388                            0                          0
119389                            0                          2

       reservation_status reservation_status_date
0               Check-Out              2015-07-01
1               Check-Out              2015-07-01
2               Check-Out              2015-07-02
3               Check-Out              2015-07-02
4               Check-Out              2015-07-03
...                   ...                     ...
119385          Check-Out              2017-09-06
119386          Check-Out              2017-09-07
119387          Check-Out              2017-09-07
119388          Check-Out              2017-09-07
119389          Check-Out              2017-09-07

[119390 rows x 32 columns]>

In [8]:
#Pandas describe function
#summary statistics of all the numerical features or columns of the data
#some of this information is not useful, like the mean or standard deviation of the arrival year,
#but knowing that information about lead time, for example, would be very useful especially for someone in the industry
data_df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,company,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,103050.000000,6797.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,86.693382,189.266735,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,110.774548,131.655015,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,62.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,14.000000,179.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,229.000000,270.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,535.000000,543.000000,391.000000,5400.000000,8.000000,5.000000

## Missing values

In [9]:
# first we need to find the number of missing values
# isnull() will return true if there is a missing value, false otherwise 
# then get all the trues in each column with sum()
data_df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [10]:
# get the percentage of values that are missing in each column 
# divide the total number of missing values by the number of total values then multiply by 100
(data_df.isnull().sum()/len(data_df))*100

hotel                              0.000000
is_canceled                        0.000000
lead_time                          0.000000
arrival_date_year                  0.000000
arrival_date_month                 0.000000
arrival_date_week_number           0.000000
arrival_date_day_of_month          0.000000
stays_in_weekend_nights            0.000000
stays_in_week_nights               0.000000
adults                             0.000000
children                           0.003350
babies                             0.000000
meal                               0.000000
country                            0.408744
market_segment                     0.000000
distribution_channel               0.000000
is_repeated_guest                  0.000000
previous_cancellations             0.000000
previous_bookings_not_canceled     0.000000
reserved_room_type                 0.000000
assigned_room_type                 0.000000
booking_changes                    0.000000
deposit_type                       0.000000
agent                             13.686238
company                           94.306893
days_in_waiting_list               0.000000
customer_type                      0.000000
adr                                0.000000
required_car_parking_spaces        0.000000
total_of_special_requests          0.000000
reservation_status                 0.000000
reservation_status_date            0.000000
dtype: float64

In [11]:
# 94% of the values in the company column are missing, so we probably want to remove that column
# can remove it using drop()
# drop() takes three arguments: the name of the column (company),
# Boolean inplace, by default is false because drop() creates a new dataframe and leaves the original dataframe unchanged 
#          if we want to modify the original dataframe directly, we must set inplace to true
# final argument is the axis, setting axis to 0 or index removes rows. setting axis to 1 or columns removes columns
data_df.drop("company", inplace=True, axis=1)

In [12]:
# viewing the results after that operation
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [13]:
# the children column has a small amount of missing values
# first look at what unique values and how many of each the column has
# value_counts() does this
data_df["children"].value_counts()

children
0.0     110796
1.0       4861
2.0       3652
3.0         76
10.0         1
Name: count, dtype: int64

In [14]:
# the most common value by far is zero
# because there are just four values missing we will just replace them with zero
# we can fill missing values with fillna()
# additional note: calling columns can be done with double quotes in square brackets (as above) or with dot notation (as below)
data_df.children = data_df.children.fillna(0)

In [15]:
#working on country column
data_df["country"].value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: count, Length: 177, dtype: int64

In [16]:
# the amount of missing values in the country column is small relative to the whole dataset (0.4% as we calculated above)
# we have two options we could use to deal with this: 
# we could replace the missing values with the mode of the column (in this case PRT for portugal),
# or we could drop all the rows with the missing values in the country column

In [17]:
# example of dropping all rows with missing data:
# using dropna() with subset argument to specify country column, otherwise it would delete all rows with any missing data
data_df = data_df.dropna(subset=["country"])

In [18]:
# show the result of that operation
# it has reduced number of rows so we know we got rid of some
data_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [19]:
# the data frame now has less rows so we know we got rid of some
# but now the indexes are mismatched
# to reset the index we use resent_index()
data_df = data_df.reset_index(drop=True)
data_df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,City Hotel,0,23,2017,August,35,30,2,5,2,0.0,0,BB,BEL,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,394.0,0,Transient,96.14,0,0,Check-Out,2017-09-06
118898,City Hotel,0,102,2017,August,35,31,2,5,3,0.0,0,BB,FRA,Online TA,TA/TO,0,0,0,E,E,0,No Deposit,9.0,0,Transient,225.43,0,2,Check-Out,2017-09-07
118899,City Hotel,0,34,2017,August,35,31,2,5,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,157.71,0,4,Check-Out,2017-09-07
118900,City Hotel,0,109,2017,August,35,31,2,5,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,89.0,0,Transient,104.40,0,0,Check-Out,2017-09-07
118901,City Hotel,0,205,2017,August,35,29,2,7,2,0.0,0,HB,DEU,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,9.0,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [20]:
# working on agent column, need to do some investigating
data_df["agent"].value_counts()

agent
9.0      31960
240.0    13871
1.0       7191
14.0      3639
7.0       3539
         ...
70.0         1
93.0         1
54.0         1
497.0        1
59.0         1
Name: count, Length: 332, dtype: int64

In [21]:
# a large amount of the bookings seem to have come from the first three agencies mentioned here
# and this column does seem to have a fair amount of missing values (13.69%)
# we can find the number of agencies in total using nunique()
data_df.agent.nunique()

332

In [22]:
# the problem in this case is we can't simply remove this column because there's a fair amount of information here
# but on the other hand, filling the value with the mean or median won't work as this is conceptually a categorical column
# filling the value with the mode might not be great either, as predicting that a certain agent booked a particular customer
# might be difficult to justify
# for now we will leave it as is and come back to it in the correlation analysis section

In [23]:
# looking at the number of missing values again, we can see we've dealt with everything except the agent column
data_df.isnull().sum()

hotel                                 0
is_canceled                           0
lead_time                             0
arrival_date_year                     0
arrival_date_month                    0
arrival_date_week_number              0
arrival_date_day_of_month             0
stays_in_weekend_nights               0
stays_in_week_nights                  0
adults                                0
children                              0
babies                                0
meal                                  0
country                               0
market_segment                        0
distribution_channel                  0
is_repeated_guest                     0
previous_cancellations                0
previous_bookings_not_canceled        0
reserved_room_type                    0
assigned_room_type                    0
booking_changes                       0
deposit_type                          0
agent                             16006
days_in_waiting_list                  0
customer_type                         0
adr                                   0
required_car_parking_spaces           0
total_of_special_requests             0
reservation_status                    0
reservation_status_date               0
dtype: int64

## Duplicates

In [24]:
# we can find duplicate values using the duplicated() function
# this outputs true if the entire row is identical to the previous row
data_df.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
118897    False
118898    False
118899    False
118900    False
118901    False
Length: 118902, dtype: bool

In [25]:
# this gets us a Boolean series, so we can sum all the true results up to see the total number
data_df.duplicated().sum()

31965

In [26]:
# before dropping a seemingly duplicate row straightaway, it's always prudent to look at the rows the function flagged as duplicates
# we can use the loc data selector to extract only those rows
# loc takes a Boolean series and filters our data frame based on the value being true or false
# the second argument will display all columns
data_df.loc[data_df.duplicated(), :]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
5,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.00,0,1,Check-Out,2015-07-03
22,Resort Hotel,0,72,2015,July,27,1,2,4,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,A,A,1,No Deposit,250.0,0,Transient,84.67,0,1,Check-Out,2015-07-07
42,Resort Hotel,0,70,2015,July,27,2,2,3,2,0.0,0,HB,ROU,Direct,Direct,0,0,0,E,E,0,No Deposit,250.0,0,Transient,137.00,0,1,Check-Out,2015-07-07
137,Resort Hotel,1,5,2015,July,28,5,1,0,2,0.0,0,BB,PRT,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,240.0,0,Transient,97.00,0,0,Canceled,2015-07-01
199,Resort Hotel,0,0,2015,July,28,7,0,1,1,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,109.80,0,3,Check-Out,2015-07-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118861,City Hotel,0,186,2017,August,35,31,0,3,2,0.0,0,BB,DEU,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient,126.00,0,2,Check-Out,2017-09-03
118864,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118865,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118866,City Hotel,0,63,2017,August,35,31,0,3,3,0.0,0,BB,SWE,Online TA,TA/TO,0,0,0,D,D,0,No Deposit,9.0,0,Transient-Party,195.33,0,2,Check-Out,2017-09-03
118885,City Hotel,0,175,2017,August,35,31,1,3,1,0.0,0,BB,NLD,Offline TA/TO,TA/TO,0,0,0,A,A,0,No Deposit,42.0,0,Transient,82.35,0,1,Check-Out,2017-09-04

In [27]:
# to drop duplicate rows we can use drop_duplicates()
# the keep argument defaults to first, which means the first duplicate occurrence is what is kept, and all others get identified and removed
# you also have the option of setting keep to last, which does the opposite
data_df.drop_duplicates(inplace=True, keep="first")

In [28]:
# output shape of the dataframe to confirm if the duplicates were actually removed
data_df.shape

(86937, 31)

## Datetime values

In [29]:
# datetime values are encountered constantly in data science projects
# in this dataset we have columns with year, month, and day, but the reservation_status_date column is an entire date
# from using info() earlier we can see this is currently being stored in the data frame as an object
# this means the dates are stored as string values
# we need to convert this to a datetime column, as date is easier to work with and manipulate rather than struggling with it as a string
# to do this, we use the to_datetime() function
data_df["reservation_status_date"] = pd.to_datetime(data_df["reservation_status_date"])

In [30]:
# checking if it has been changed
data_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 86937 entries, 0 to 118901
Data columns (total 31 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           86937 non-null  object
 1   is_canceled                     86937 non-null  int64
 2   lead_time                       86937 non-null  int64
 3   arrival_date_year               86937 non-null  int64
 4   arrival_date_month              86937 non-null  object
 5   arrival_date_week_number        86937 non-null  int64
 6   arrival_date_day_of_month       86937 non-null  int64
 7   stays_in_weekend_nights         86937 non-null  int64
 8   stays_in_week_nights            86937 non-null  int64
 9   adults                          86937 non-null  int64
 10  children                        86937 non-null  float64
 11  babies                          86937 non-null  int64
 12  meal                            86937 non-null  object
 13  country                         86937 non-null  object
 14  market_segment                  86937 non-null  object
 15  distribution_channel            86937 non-null  object
 16  is_repeated_guest               86937 non-null  int64
 17  previous_cancellations          86937 non-null  int64
 18  previous_bookings_not_canceled  86937 non-null  int64
 19  reserved_room_type              86937 non-null  object
 20  assigned_room_type              86937 non-null  object
 21  booking_changes                 86937 non-null  int64
 22  deposit_type                    86937 non-null  object
 23  agent                           75073 non-null  float64
 24  days_in_waiting_list            86937 non-null  int64
 25  customer_type                   86937 non-null  object
 26  adr                             86937 non-null  float64
 27  required_car_parking_spaces     86937 non-null  int64
 28  total_of_special_requests       86937 non-null  int64
 29  reservation_status              86937 non-null  object
 30  reservation_status_date         86937 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(16), object(11)
memory usage: 21.2+ MB

In [31]:
# the [ns] here indicates that's a nanosecond-based time format, telling us the precision of the format
# we can do multiple types of analysis once we've converted our date into the correct format
# we can find the minimum and maximum date value, slice the values to look at particular instances between dates, etc.

In [32]:
# get year, month, date from our date column
# to extract the year we'll create a new column and name it appropriately (reservation_status_year), then extract the value to it
data_df["reservation_status_year"] = data_df["reservation_status_date"].dt.year

#and do the same for month and day
data_df["reservation_status_month"] = data_df["reservation_status_date"].dt.month
data_df["reservation_status_day"] = data_df["reservation_status_date"].dt.day
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year,reservation_status_month,reservation_status_day
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015,7,3

In [33]:
# if we want, we can even extract the week of the year, or day of the week as well
# note: original tutorial used dt.week, but that is since deprecated, so dt.isocalendar().week was used instead as it's now correct
data_df["res_week_of_year"] = data_df["reservation_status_date"].dt.isocalendar().week
data_df["res_day_of_week"] = data_df["reservation_status_date"].dt.dayofweek
data_df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,agent,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1,27,2
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01,2015,7,1,27,2
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2,27,3
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,304.0,0,Transient,75.0,0,0,Check-Out,2015-07-02,2015,7,2,27,3
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,240.0,0,Transient,98.0,0,1,Check-Out,2015-07-03,2015,7,3,27,4

In [34]:
# once we've extracted everything we need from the datetime column, we can safely drop it
data_df.drop("reservation_status_date", inplace=True, axis=1)

## Illogical values

In [35]:
# earlier we saw we had records with 0 adults, which makes no sense 
# checking how many rows like that are present
(data_df["adults"]==0).sum()

380

In [36]:
# dropping those rows
data_df.drop(data_df[data_df["adults"] == 0].index, inplace=True)

In [37]:
# checking that was done correctly
(data_df["adults"]==0).sum()

0

## Dealing with categorical data

In [38]:
# creating a data frame with all the categorical features from our original data frame
# first, create a list of all the columns in the original data frame that is type object using list comprehension
cat_cols = [col for col in data_df.columns if data_df[col].dtype=="object"]
cat_cols

['hotel',
 'arrival_date_month',
 'meal',
 'country',
 'market_segment',
 'distribution_channel',
 'reserved_room_type',
 'assigned_room_type',
 'deposit_type',
 'customer_type',
 'reservation_status']

In [39]:
# filter out a categorical feature data frame from our original data frame
cat_df = data_df[cat_cols]
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,July,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,July,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,July,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,July,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [40]:
# printing unique values of each column
for col in cat_df.columns:
    print(f"{col}: \n{cat_df[col].unique()}\n")

hotel:
['Resort Hotel' 'City Hotel']

arrival_date_month:
['July' 'August' 'September' 'October' 'November' 'December' 'January'
 'February' 'March' 'April' 'May' 'June']

meal:
['BB' 'FB' 'HB' 'SC' 'Undefined']

country:
['PRT' 'GBR' 'USA' 'ESP' 'IRL' 'FRA' 'ROU' 'NOR' 'OMN' 'ARG' 'POL' 'DEU'
 'BEL' 'CHE' 'CN' 'GRC' 'ITA' 'NLD' 'DNK' 'RUS' 'SWE' 'AUS' 'EST' 'CZE'
 'BRA' 'FIN' 'MOZ' 'BWA' 'LUX' 'SVN' 'ALB' 'IND' 'CHN' 'MEX' 'MAR' 'UKR'
 'SMR' 'LVA' 'PRI' 'SRB' 'CHL' 'AUT' 'BLR' 'LTU' 'TUR' 'ZAF' 'AGO' 'ISR'
 'CYM' 'ZMB' 'CPV' 'ZWE' 'DZA' 'KOR' 'CRI' 'HUN' 'ARE' 'TUN' 'JAM' 'HRV'
 'HKG' 'IRN' 'GEO' 'AND' 'GIB' 'URY' 'JEY' 'CAF' 'CYP' 'COL' 'GGY' 'KWT'
 'NGA' 'MDV' 'VEN' 'SVK' 'FJI' 'KAZ' 'PAK' 'IDN' 'LBN' 'PHL' 'SEN' 'SYC'
 'AZE' 'BHR' 'NZL' 'THA' 'DOM' 'MKD' 'MYS' 'ARM' 'JPN' 'LKA' 'CUB' 'CMR'
 'BIH' 'MUS' 'COM' 'SUR' 'UGA' 'BGR' 'CIV' 'JOR' 'SYR' 'SGP' 'BDI' 'SAU'
 'VNM' 'PLW' 'QAT' 'EGY' 'PER' 'MLT' 'MWI' 'ECU' 'MDG' 'ISL' 'UZB' 'NPL'
 'BHS' 'MAC' 'TGO' 'TWN' 'DJI' 'STP' 'KNA' 'ETH' 'IRQ' 'HND' 'RWA' 'KHM'
 'MCO' 'BGD' 'IMN' 'TJK' 'NIC' 'BEN' 'VGB' 'TZA' 'GAB' 'GHA' 'TMP' 'GLP'
 'KEN' 'LIE' 'GNB' 'MNE' 'UMI' 'MYT' 'FRO' 'MMR' 'PAN' 'BFA' 'LBY' 'MLI'
 'NAM' 'BOL' 'PRY' 'BRB' 'ABW' 'AIA' 'SLV' 'DMA' 'PYF' 'GUY' 'LCA' 'ATA'
 'GTM' 'ASM' 'MRT' 'NCL' 'KIR' 'SDN' 'ATF' 'SLE' 'LAO']

market_segment:
['Direct' 'Corporate' 'Online TA' 'Offline TA/TO' 'Complementary' 'Groups'
 'Undefined' 'Aviation']

distribution_channel:
['Direct' 'Corporate' 'TA/TO' 'Undefined' 'GDS']

reserved_room_type:
['C' 'A' 'D' 'E' 'G' 'F' 'H' 'L' 'B']

assigned_room_type:
['C' 'A' 'D' 'E' 'G' 'F' 'I' 'B' 'H' 'L' 'K']

deposit_type:
['No Deposit' 'Refundable' 'Non Refund']

customer_type:
['Transient' 'Contract' 'Transient-Party' 'Group']

reservation_status:
['Check-Out' 'Canceled' 'No-Show']

In [41]:
# encode arrival date month
# we will manually map each of these months to a number, starting with 1 for january
# using dictionary and map()
# map() takes a dictionary as an argument and returns a new column the same length as the original column,
# in this instance replacing month names with the corresponding numerical values
cat_df["arrival_date_month"] = cat_df["arrival_date_month"].map({"January":1, "February":2, "March":3, "April":4, "May":5, "June":6,
                                                                    "July":7, "August":8, "September":9, "October":10, "November":11, 
                                                                 "December":12})

C:\Users\baile\AppData\Local\Temp\ipykernel_19100\1747176079.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["arrival_date_month"] = cat_df["arrival_date_month"].map({"January":1, "February":2, "March":3, "April":4, "May":5, "June":6,

In [42]:
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,Resort Hotel,7,BB,PRT,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,Resort Hotel,7,BB,GBR,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,Resort Hotel,7,BB,GBR,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,Resort Hotel,7,BB,GBR,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [43]:
# working on country and hotel columns
# country can't be one-hot encoded since it has so many unique values, will create a ton of new columns, so we'll label encode
# hotel has only 2 unique values, so we can use label encoding also, those will end up encoded as 0 and 1
# import LabelEncoder class from scikit learn (python data science library)
from sklearn.preprocessing import LabelEncoder

# initialize label encoder class
le = LabelEncoder()

# use fit_transform() from LabelEncoder on country feature
# fit_transform() does two things: 
# 'fit' component takes in the entire feature and maps each unique categorical value to a numerical value
# 'transform' makes the intended change
cat_df["country"] = le.fit_transform(cat_df["country"])

# same thing for hotel feature
cat_df["hotel"] = le.fit_transform(cat_df["hotel"])

C:\Users\baile\AppData\Local\Temp\ipykernel_19100\4044419356.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["country"] = le.fit_transform(cat_df["country"])
C:\Users\baile\AppData\Local\Temp\ipykernel_19100\4044419356.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cat_df["hotel"] = le.fit_transform(cat_df["hotel"])

In [44]:
cat_df.head()

,hotel,arrival_date_month,meal,country,market_segment,distribution_channel,reserved_room_type,assigned_room_type,deposit_type,customer_type,reservation_status
0,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out
1,1,7,BB,135,Direct,Direct,C,C,No Deposit,Transient,Check-Out
2,1,7,BB,59,Direct,Direct,A,C,No Deposit,Transient,Check-Out
3,1,7,BB,59,Corporate,Corporate,A,A,No Deposit,Transient,Check-Out
4,1,7,BB,59,Online TA,TA/TO,A,A,No Deposit,Transient,Check-Out

In [45]:
# for the rest of the features we'll use one-hot encoding
# using get_dummies() from pandas to perform one-hot encoding
# we give the function the data frame as the input, and all the columns that need to undergo one-hot encoding
cat_df = pd.get_dummies(data=cat_df, columns=["meal", "market_segment", "distribution_channel",
                                             "reserved_room_type", "assigned_room_type", "customer_type", 
                                             "deposit_type", "reservation_status"])

In [46]:
cat_df

,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
1,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
2,1,7,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
3,1,7,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
4,1,7,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,8,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118898,0,8,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118899,0,8,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118900,0,8,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118901,0,8,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False

In [48]:
# creating a numerical data frame by dropping all the categorical features
# we could do this to our original data frame, but we're doing it this way to avoid any sort of confusion with the data frame means
num_df = data_df.drop(columns=cat_cols, axis=1)

In [49]:
num_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,NaN,0,0.00,0,0,2015,7,1,27,2
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,NaN,0,0.00,0,0,2015,7,1,27,2
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,NaN,0,75.00,0,0,2015,7,2,27,3
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,2015,7,2,27,3
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,2015,7,3,27,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,2017,9,6,36,2
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,2017,9,7,36,3
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,2017,9,7,36,3
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,2017,9,7,36,3
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,2017,9,7,36,3

In [50]:
# create final data frame by concatenating the two data frames
# axis indicates the axis we want to concatenate along, 0 for row-wise, 1 for column-wise
final_df = pd.concat([num_df, cat_df], axis=1)

In [51]:
final_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,NaN,0,0.00,0,0,2015,7,1,27,2,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,NaN,0,0.00,0,0,2015,7,1,27,2,1,7,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,NaN,0,75.00,0,0,2015,7,2,27,3,1,7,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,2015,7,2,27,3,1,7,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,2015,7,3,27,4,1,7,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,2017,9,6,36,2,0,8,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,2017,9,7,36,3,0,8,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,2017,9,7,36,3,0,8,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,2017,9,7,36,3,0,8,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,2017,9,7,36,3,0,8,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False

## Correlation Analysis

In [52]:
# create a correlation matrix using pandas corr()
# corr() calculates the correlation coefficients between all pairs of features in the data frame 
# and returns a data frame with the same shape as the input data frame
# absolute function ( abs() ) makes every value absolute, as correlation coefficients can be negative 
corr_matrix = final_df.corr().abs()
corr_matrix

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_year,reservation_status_month,reservation_status_day,res_week_of_year,res_day_of_week,hotel,arrival_date_month,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_Direct,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_G,assigned_room_type_H,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Non Refund,deposit_type_Refundable,reservation_status_Canceled,reservation_status_Check-Out,reservation_status_No-Show
is_canceled,1.000000,0.182933,0.087449,0.001180,0.005381,0.060386,0.083838,0.081074,0.066124,0.020744,0.089305,0.050999,0.050608,0.093669,0.043246,0.004578,0.125962,0.184113,0.122370,0.009340,0.099776,0.011826,0.104362,0.122361,0.069262,0.003420,0.097385,0.039691,0.000160,0.004387,0.061847,0.018203,0.008811,0.030720,0.075168,0.112626,0.002860,0.124466,0.210774,0.007783,0.079974,0.118183,0.007906,0.149952,0.008907,0.044359,0.005323,0.011108,0.028686,0.001508,0.010914,0.029534,0.024513,0.001066,0.074359,0.024815,0.032891,0.042519,0.026115,0.013309,0.010418,0.015896,0.037137,0.022427,0.005504,0.048876,0.031168,0.128014,0.109269,0.156617,0.165237,0.002606,0.970963,1.000000,0.175584
lead_time,0.182933,1.000000,0.138387,0.101223,0.009439,0.235428,0.312606,0.141754,0.022918,0.003702,0.146763,0.005628,0.076486,0.080710,0.025703,0.132260,0.018432,0.085673,0.032062,0.076291,0.057707,0.001008,0.053913,0.025164,0.037349,0.106253,0.095810,0.064420,0.013080,0.138679,0.054920,0.008200,0.045107,0.069017,0.162540,0.141971,0.193578,0.132007,0.004427,0.004394,0.129726,0.132654,0.031939,0.193995,0.005049,0.024460,0.033427,0.001647,0.016797,0.025993,0.025027,0.000036,0.001893,0.007756,0.041851,0.014206,0.004921,0.039835,0.011599,0.030116,0.008252,0.005195,0.008984,0.019815,0.003166,0.065756,0.025530,0.162580,0.151732,0.168096,0.167832,0.026667,0.193604,0.182933,0.033650
arrival_date_year,0.087449,0.138387,1.000000,0.513891,0.009932,0.005044,0.003834,0.037800,0.042053,0.023090,0.024346,0.054025,0.028222,0.009169,0.020022,0.027753,0.176448,0.038919,0.064083,0.959861,0.418558,0.009800,0.445193,0.005554,0.077939,0.499462,0.130414,0.075154,0.030937,0.014351,0.117270,0.015874,0.018841,0.018670,0.035283,0.013179,0.060272,0.108291,0.134863,0.008488,0.035708,0.025056,0.016086,0.040770,0.013421,0.056915,0.037962,0.017394,0.049397,0.020975,0.010392,0.014122,0.000758,0.014702,0.020369,0.059257,0.000346,0.001145,0.004175,0.007263,0.003083,0.004830,0.004667,0.006125,0.006002,0.168153,0.017444,0.170529,0.094544,0.018924,0.019296,0.001758,0.091509,0.087449,0.011802
arrival_date_week_number,0.001180,0.101223,0.513891,1.000000,0.092946,0.026872,0.028235,0.025066,0.013653,0.013597,0.038601,0.006453,0.020898,0.012378,0.018117,0.013215,0.098556,0.008868,0.046004,0.461224,0.802035,0.031997,0.824767,0.019180,0.019122,0.995061,0.023499,0.004374,0.012382,0.033360,0.038739,0.010381,0.006710,0.011887,0.005950,0.009963,0.013235,0.042273,0.029762,0.001818,0.015207,0.005800,0.003553,0.003237,0.002541,0.008416,0.010436,0.009255,0.001155,0.002820,0.007851,0.001858,0.007826,0.001827,0.008954,0.017753,0.010471,0.007936,0.001483,0.007374,0.005959,0.011371,0.004058,0.005535,0.000538,0.091170,0.013617,0.059934,0.013904,0.000519,0.003975,0.013992,0.005788,0.001180,0.018897
arrival_date_day_of_month,0.005381,0.009439,0.009932,0.092946,1.000000,0.017182,0.027836,0.000607,0.014892,0.000594,0.004738,0.008761,0.000689,0.007139,0.009265,0.006116,0.022640,0.008680,0.002002,0.013696,0.002055,0.335898,0.047585,0.005521,0.009030,0.000076,0.005882,0.008802,0.002996,0.002357,0.011408,0.005521,0.001288,0.005004,0.004100,0.004987,0.008445,0.001018,0.005339,0.006428,0.012224,0.009771,0.001620,0.001254,0.008272,0.019124,0.004797,0.001070,0.008277,0.010573,0.008963,0.005211,0.002800,0.004695,0.013517,0.004878,0.001045,0.003013,0.009522,0.008009,0.003001,0.002998,0.003333,0.005913,0.000456,0.019189,0.000959,0.004972,0.005188,0.011670,0.003034,0.028535,0.004592,0.005381,0.003547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
deposit_type_Non Refund,0.165237,0.167832,0.019296,0.003975,0.003034,0.029650,0.031979,0.031208,0.031005,0.010507,0.016078,0.090529,0.001774,0.028286,0.021511,0.112604,0.028904,0.032449,0.090392,0.067777,0.009148,0.002162,0.008914,0.042328,0.045439,0.004036,0.109584,0.016335,0.024233,0.010278,0.037381,0.001636,0.005634,0.009842,0.008020,0.040191,0.275293,0.034903,0.128916,0.000529,0.014504,0.029917,0.005041,0.018538,0.000837,0.064774,0.007227,0.010330,0.049294,0.011645,0.019575,0.016399,0.006601,0.000917,0.080431,0.007458,0.011372,0.056775,0.015973,0.019243,0.018276,0.007589,0.005306,0.005096,0.000374,0.005427,0.008676,0.001012,0.003841,0.951491,1.000000,0.003874,0.168947,0.165237,0.005996
deposit_type_Refundable,0.002606,0.026667,0.001758,0.013992,0.028535,0.002160,0.003215,0.001012,0.006914,0.003357,0.000259,0.002877,0.003049,0.023708,0.016450,0.023663,0.017241,0.012930,0.021270,0.002493,0.006991,0.018616,0.009408,0.010561,0.034142,0.017117,0.002149,0.014094,0.002274,0.008795,0.009098,0.002649,0.001800,0.003144,0.003071,0.008045,0.105002,0.011746,0.033062,0.000169,0.004326,0.041942,0.001610,0.034114,0.000267,0.014249,0.003379,0.012460,0.011864,0.004420,0.004591,0.005463,0.002929,0.000293,0.003318,0.002460,0.028286,0.009416,0.003822,0.005691,0.006042,0.003181,0.002232,0.001628,0.000120,0.003299,0.018223,0.062282,0.067320,0.303989,0.003874,1.000000,0.002460,0.002606,0.000747
reservation_status_Canceled,0.970963,0.193604,0.091509,0.005788,0.004592,0.058112,0.082611,0.089174,0.067113,0.020125,0.091195,0.053424,0.050518,0.094243,0.039836,0.006615,0.131154,0.178767,0.120441,0.011451,0.098117,0.013038,0.102531,0.124916,0.063354,0.008362,0.085887,0.041749,0.000494,0.000018,0.060087,0.017166,0.013229,0.032033,0.078599,0.117486,0.000506,0.127189,0.217227,0.008016,0.083933,0.123096,0.008528,0.156581,0.009228,0.047402,0.005173,0.011929,0.030622,0.000734,0.010423,0.032474,0.025140,0.001300,0.074195,0.025352,0.033025,0.042037,0.026205,0.015204,0.012416,0.016159,0.036801,0.022648,0.005668,0.047941,0.030855,0.127890,0.109716,0.160196,0.168947,0.002460,1.000000,0.970963,0.065027
reservation_status_Check-Out,1.000000,0.182933,0.087449,0.001180,0.005381,0.060386,0.083838,0.081074,0.066124,0.020744,0.089305,0.050999,0.050608,0.093669,0.043246,0.004578,0.125962,0.184113,0.122370,0.009340,0.099776,0.011826,0.104362,0.122361,0.069262,0.003420,0.097385,0.039691,0.000160,0.004387,0.061847,0.018203,0.008811,0.030720,0.075168,0.112626,0.002860,0.124466,0.210774,0.007783,0.079974,0.118183,0.007906,0.149952,0.008907,0.044359,0.005323,0.011108,0.028686,0.001508,0.010914,0.029534,0.024513,0.001066,0.074359,0.024815,0.032891,0.042519,0.026115,0.013309,0.010418,0.015896,0.037137,0.022427,0.005504,0.048876,0.031168,0.128014,0.109269,0.156617,0.165237,0.002606,0.970963,1.000000,0.175584
reservation_status_No-Show,0.175584,0.033650,0.011802,0.018897,0.003547,0.012746,0.009751,0.028787,0.000360,0.003710,0.002768,0.007119,0.003210,0.002894,0.016870,0.008124,0.014298,0.032327,0.014805,0.008165,0.012423,0.004324,0.013388,0.003648,0.028201,0.020148,0.052775,0.006244,0.001367,0.018374,0.010712,0.005286,0.017687,0.003680,0.009903,0.013684,0.009848,0.004224,0.014731,0.000521,0.011802,0.013587,0.002115,0.018867,0.000824,0.010035,0.000914,0.002755,0.006359,0.003268,0.002633,0.010441,0.001208,0.000903,0.004845,0.000818,0.001292,0.004369,0.001093,0.007054,0.007640,0.000191,0.003468,0.000350,0.000369,0.006592,0.003037,0.007689,0.004288,0.005943,0.005996,0.000747,0.065027,0.175584,1.000000

In [53]:
# setting the correlation coefficient threshold
# which anything over will be considered highly correlated 
# this value is open to modifications based on trial and error
threshold = 0.85

In [54]:
# create a mask to identify highly correlated features

import numpy as np

# np.ones() creates an array of 1s with the same shape as corr_matrix
# np.triu() returns the upper triangular portion of this array, excluding the diagonal elements and everything below it
# here, k controls what elements should be zeroed out with respect to the diagonal
# k = 0 is the main diagonal; k=1 excludes the main diagonal and everything below it
# the resulting array is then cast to a Boolean array using astype(), so elements in the upper triangular portion are true,
# while elements in the lower triangular portion are false
# the resulting upper triangular array is then used as a mask to select the upper triangular portion of corr_matrix using where()
# where() sets all values in corr_matrix that correspond to false in the upper triangular to NaN
# the resulting matrix stored in the upper variable is a copy of corr_matrix with all elements in the lower triangular portion set to NaN
# we exclude diagonal elements in the lower portion of the triangle because diagonal values will always be 1 because that's 
# the correlation of the feature with itself
# everything below the diagonal is excluded because it's a mirror image of the upper triangular as correlation is a symmetric measure

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

In [55]:
# ensuring only 1 of the highly correlated features gets dropped
# first create an empty list called to_drop to keep track of the features we want to drop from the data frame
to_drop = []

# then, iterate over the upper triangle of the correlation matrix using two nested loops, one for rows and one for columns
# for each pair of features, check if the absolute value of the correlation coefficient is greater than or equal to the threshold
# if it is, we add the name wih the second feature of the pair, the one with the higher index, to the to_drop list
for i in range (len(corr_matrix.columns)):
    for j in range(i):
        if abs(corr_matrix.iloc[i, j]) >= threshold:
            colname = corr_matrix.columns[i]
            to_drop.append(colname)

In [56]:
to_drop

['reservation_status_year',
 'res_week_of_year',
 'arrival_date_month',
 'distribution_channel_Direct',
 'assigned_room_type_G',
 'assigned_room_type_H',
 'deposit_type_Non Refund',
 'reservation_status_Canceled',
 'reservation_status_Check-Out',
 'reservation_status_Check-Out']

In [57]:
# drop all the columns in the list from the data frame
final_df.drop(columns=to_drop, inplace=True)

In [58]:
# returning to agent feature from 'missing values' section
# looking at how many missing values it has
final_df.agent.isnull().sum()

11800

In [59]:
# in this case, we don't want to just delete the column, and filling with guesses would be difficult to justify
# it can be useful to look online for additional resources, or talk to your organization's domain expert
# with this dataset we have an article that the dataset is based on
# in this article they clarify for some categorical variables in this dataset, NULL should not be interpreted as 
# missing data but rather as 'not applicable'
# so for agent, a NULL value indicates the booking did not come from a travel agent

# in this case we just need to impute the missing values in the agent column with a 0 so a machine learning model
# or person looking at the data can identify it as a separate class
final_df["agent"] = final_df["agent"].fillna(0)

In [60]:
final_df

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,agent,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests,reservation_status_month,reservation_status_day,res_day_of_week,hotel,country,meal_BB,meal_FB,meal_HB,meal_SC,meal_Undefined,market_segment_Aviation,market_segment_Complementary,market_segment_Corporate,market_segment_Direct,market_segment_Groups,market_segment_Offline TA/TO,market_segment_Online TA,market_segment_Undefined,distribution_channel_Corporate,distribution_channel_GDS,distribution_channel_TA/TO,distribution_channel_Undefined,reserved_room_type_A,reserved_room_type_B,reserved_room_type_C,reserved_room_type_D,reserved_room_type_E,reserved_room_type_F,reserved_room_type_G,reserved_room_type_H,reserved_room_type_L,assigned_room_type_A,assigned_room_type_B,assigned_room_type_C,assigned_room_type_D,assigned_room_type_E,assigned_room_type_F,assigned_room_type_I,assigned_room_type_K,assigned_room_type_L,customer_type_Contract,customer_type_Group,customer_type_Transient,customer_type_Transient-Party,deposit_type_No Deposit,deposit_type_Refundable,reservation_status_No-Show
0,0,342,2015,27,1,0,0,2,0.0,0,0,0,0,3,0.0,0,0.00,0,0,7,1,2,1,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
1,0,737,2015,27,1,0,0,2,0.0,0,0,0,0,4,0.0,0,0.00,0,0,7,1,2,1,135,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
2,0,7,2015,27,1,0,1,1,0.0,0,0,0,0,0,0.0,0,75.00,0,0,7,2,3,1,59,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,True,False,False
3,0,13,2015,27,1,0,1,1,0.0,0,0,0,0,0,304.0,0,75.00,0,0,7,2,3,1,59,True,False,False,False,False,False,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
4,0,14,2015,27,1,0,2,2,0.0,0,0,0,0,0,240.0,0,98.00,0,1,7,3,4,1,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118897,0,23,2017,35,30,2,5,2,0.0,0,0,0,0,0,394.0,0,96.14,0,0,9,6,2,0,15,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
118898,0,102,2017,35,31,2,5,3,0.0,0,0,0,0,0,9.0,0,225.43,0,2,9,7,3,0,56,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,True,False,True,False,False
118899,0,34,2017,35,31,2,5,2,0.0,0,0,0,0,0,9.0,0,157.71,0,4,9,7,3,0,43,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,False,True,False,False
118900,0,109,2017,35,31,2,5,2,0.0,0,0,0,0,0,89.0,0,104.40,0,0,9,7,3,0,59,True,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False
118901,0,205,2017,35,29,2,7,2,0.0,0,0,0,0,0,9.0,0,151.20,0,2,9,7,3,0,43,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,True,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False

In [61]:
# now this data frame could be safely fed into a machine learning model or send for further analysis
# this is not a comprehensive filtering and cleaning job but we've gone through the essentials